
import { Theme } from "../../assets/theme/theme.slint";
import { ImageScreen } from "../../components/lock-screen/image-screen/ImageScreen.slint";
import { PasswordScreen } from "../../components/lock-screen/password-screen/PasswordScreen.slint";
import { StatusScreen } from "../../components/lock-screen/status-screen/StatusScreen.slint";
export component Lock inherits Window {
    width: 800px;
    height: 480px;
    background: Theme.palette.gray-bg;

    in-out property <string> entered_password: "";
    in-out property <int> current-tab: 1;

    ImageScreen {
        width: 100%;
        height: 100%;
        visible: current-tab == 1;
        onImageClick => {
            current-tab = 2
        }
    }

    StatusScreen {
        width: 100%;
        height: 100%;
        visible: current-tab == 2;
        onLockClick => {
            current-tab = 3
        }
    }

    PasswordScreen {
        width: 100%;
        height: 100%;
        visible: current-tab == 3;
        entered_password <=> root.entered_password;
    }
}
