
export struct Spaces {
    small: length,
    medium: length,
    large: length,
}
export struct Palette {
    // bg
    gray-bg: brush,
    bg:{
        white:brush,
        white50:brush,
        white-1:brush,
        white-2:brush,
        success:brush,
        black-1:brush,
    },
    border: {
        gray: brush,
    },

    text: {
        white-1:brush,
        gray-1: brush,
        gray-2:brush,
        gray-3:brush,
        gray-4:brush,
    },
}
export global Theme {
    in property <Palette> palette: {
        gray-bg: #DBDBDB,
        bg:{
            white: #EFEFEF,
            white50:#EFEFEF80,
            white-1:#E5E5E5,
            white-2:#e4e4e4,
            success: #14FF00,
            black-1:#404040,
        },
        border: {
            gray: #e0e0e0,
        },
        text: { white-1: #EFEFEF, gray-1: #404040, gray-2:#222222, gray-3:#8A8A8A, gray-4:#DBDBDB }
    };
}
