import { VerticalBox, TextEdit, HorizontalBox, Button, LineEdit } from "std-widgets.slint";
import { KeyButton } from "KeyButton.slint";
import { Theme } from "../../../assets/theme/theme.slint";

export component PasswordScreen inherits Window {
    width: 800px;
    height: 480px;
    background: Theme.palette.gray-bg;

    // Property to store the entered numbers
    in-out property <string> entered_password: "";

    VerticalBox {
        HorizontalBox {
            padding: 0;
            height: 164px;
            Rectangle {
                border-radius: 20px;
                background: Theme.palette.bg.white;
                HorizontalBox {
                    y: 0;
                    height: 89.74px;
                    padding-top: 30px;
                    Text {
                        text: "Enter Password";
                        font-size: 20px;
                        color: Theme.palette.text.gray-2;
                        font-family: "Sailec";
                        font-weight: 400;
                        height: 35px;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                }

                HorizontalBox {
                    y: 89.74px;
                    height: 60px;
                    alignment: center;
                    padding-top: 25px;

                    LineEdit {
                        padding: 20px;
                        horizontal-alignment: center;
                        input-type: password;
                        read-only: true;
                        text: entered_password;
                    }
                }
            }
        }

        HorizontalBox {
            padding: 0;
            Rectangle {
                border-radius: 20px;
                border-color: #EFEFEF;
                border-width: 4px;
                VerticalBox {
                    x: 0px;
                    width: 611px;
                    keyGrid := GridLayout {
                        spacing: 8px;
                        Row {
                            KeyButton {
                                keyNumber: "1";
                                keyPressed => {
                                    entered_password += self.keyNumber;
                                }
                            }

                            KeyButton {
                                keyNumber: "2";
                                keyPressed => {
                                    entered_password += self.keyNumber;
                                }
                            }

                            KeyButton {
                                keyNumber: "3";
                                keyPressed => {
                                    entered_password += self.keyNumber;
                                }
                            }

                            KeyButton {
                                keyNumber: "4";
                                keyPressed => {
                                    entered_password += self.keyNumber;
                                }
                            }

                            KeyButton {
                                keyNumber: "5";
                                keyPressed => {
                                    entered_password += self.keyNumber;
                                }
                            }
                        }

                        Row {
                            KeyButton {
                                keyNumber: "6";
                                keyPressed => {
                                    entered_password += self.keyNumber;
                                }
                            }

                            KeyButton {
                                keyNumber: "7";
                                keyPressed => {
                                    entered_password += self.keyNumber;
                                }
                            }

                            KeyButton {
                                keyNumber: "8";
                                keyPressed => {
                                    entered_password += self.keyNumber;
                                }
                            }

                            KeyButton {
                                keyNumber: "9";
                                keyPressed => {
                                    entered_password += self.keyNumber;
                                }
                            }

                            KeyButton {
                                keyNumber: "0";
                                keyPressed => {
                                    entered_password += self.keyNumber;
                                }
                            }
                        }
                    }
                }

                VerticalBox {
                    x: keyGrid.width + keyGrid.spacing;
                    width: 180px;

                    Rectangle {
                        accessible-role: button;
                        background: #EFEFEF;
                        border-radius: 10px;
                        padding: 10px;
                        Image {
                            source: @image-url("../../../assets/images/backspace-icon.svg");
                        }

                        TouchArea {
                            clicked => {
                                entered_password = ""
                            }
                        }
                    }
                }
            }
        }
    }
}
