component AppSelectCard inherits Rectangle {
    // in-out property text <=> txt.text;
    // in-out property img <=> img.source;
    // in-out property imgWidth <=> img.width;
    // in-out property imgHeight <=> img.height;


    callback clicked <=> touch.clicked;
    // callback focus <=> touch.clicked;
    // accessible-delegate-focus: 1;
    // accessible-role: button;
    // accessible-delegate-focus: 1;

    // border-radius: root.height / 2;
    // border-width: 1px;
    // border-color: root.background.darker(25%);
    // background: touch.pressed ? #6b8282 : touch.has-hover ? #6c616c :  #ffffff;
    // height: txt.preferred-height * 1.33;
    // min-width: txt.preferred-width + 20px;


    // txt := Text {
        // x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
        // y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
        // color: touch.pressed ? #fff : #0b0b0b;
    // }

    // img := Image {
    //     x:10px;
    // }
    touch := TouchArea { }
}