import { HorizontalBox } from "std-widgets.slint";
import { ButtonBox } from "button-box.slint";
import { Theme } from "../../assets/theme/theme.slint";



export component Header {

    // get from parent
    in-out property <string> currentPage:"";
    in-out property <string> previousPage:"";

    callback backClick;

    HorizontalBox {
        padding: 0;
        spacing: 20px;
        alignment: end;

        if currentPage != "HomeMain":  ButtonBox {
            width: 100px;
            height: 40px;
            border-radius: 100px;
            background: Theme.palette.bg.white;
            Image {
                x: 10px;
                source: @image-url("../../assets/images/back-btn.svg");
            }

            Text {
                text: currentPage;
            }

            clicked => {
                currentPage = previousPage;
            }
        }

        HorizontalBox {
            alignment: end;
            padding: 0;
            width: 780px - 120px;

            // wifi icon
            Image {
                source: @image-url("../../assets/images/wifi-black.svg");
                width: 40px;
                height: 40px;
            }

            // time
            Rectangle {
                width: 154px;
                height: 40px;
                background: Theme.palette.bg.white;
                border-radius: 20.50px;
                Text {
                    text: "16 : 38";
                    font-family: "Sailec-Light";
                    font-size: 20px;
                    font-weight: 600;
                }
            }

            // connection
            Rectangle {
                width: 40px;
                height: 40px;
                background: Theme.palette.bg.white;
                border-radius: 500px;
                padding: 7.5px;

                Rectangle {
                    width: 25px;
                    height: 25px;
                    background: Theme.palette.bg.success;
                    border-radius: 500px;
                }
            }
        }
    }
}
