import { ScrollView, HorizontalBox, GridBox, VerticalBox } from "std-widgets.slint";
import { Theme } from "../../../../assets/theme/theme.slint";
import { Header } from "../../header.slint";

component Icon inherits VerticalBox {
    height: 40px;
    width: 40px;
    callback clicked <=> touch.clicked;
    in property <image> sourceUrl;
    accessible-role: button;

    touch := TouchArea {
        Image {
            source: sourceUrl;
        }
    }
}

export component ActiveAlarm inherits Rectangle {
    height: 82px;
    width: 760px;
    border-radius: 20px;
    background: Theme.palette.bg.white;

    in property <string> alarmName;
    in property <string> alarmType;
    callback clicked <=> icon.clicked;
    HorizontalLayout {
        padding: 10px;
        y: 10px;
        VerticalBox {
            padding: 10px;
            Text {
                text: alarmName;
                font-weight: 400;
                font-size: 20px;
                font-family: "Sailec-Medium";
                color: Theme.palette.text.gray-2;
            }
        }

        VerticalBox {
            padding: 10px;
            Text {
                text: alarmType;
                font-weight: 400;
                font-size: 20px;
                font-family: "Sailec-Light";
                color: Theme.palette.text.gray-3;
            }
        }

        icon := Icon {
            sourceUrl: @image-url("../../../../assets/images/right.svg");
        }
    }
}

component DisabledAlarm inherits Rectangle {
    height: 82px;
    width: 760px;
    border-radius: 20px;
    background: Theme.palette.bg.white;

    in property <string> alarmName;
    in property <string> alarmType;
    callback clicked <=> icon.clicked;
    HorizontalLayout {
        padding: 10px;
        y: 10px;
        VerticalBox {
            padding: 10px;
            Text {
                text: alarmName;
                font-weight: 400;
                font-size: 20px;
                font-family: "Sailec-Medium";
                color: Theme.palette.text.gray-3;
            }
        }

        VerticalBox {
            padding: 10px;
            Text {
                text: alarmType;
                font-weight: 400;
                font-size: 20px;
                font-family: "Sailec-Light";
                color: Theme.palette.text.gray-4;
            }
        }

        icon := Icon {
            sourceUrl: @image-url("../../../../assets/images/info-icon.svg");
        }
    }
}

export component StoricoAllarmi inherits Window {
    background: Theme.palette.gray-bg;

    in-out property <string> currentPage;
    in-out property <string> selectedAlarmName;
    in-out property <string> selectedAlarmType;
    VerticalBox {
        Header {
            currentPage <=> root.currentPage;
            previousPage: "SettingMachina";
        }

        ScrollView {
            width: 100%;
            height: 412px;

            HorizontalBox {
                padding: 0;
                GridBox {
                    padding: 0;
                    Row {
                        ActiveAlarm {
                            alarmName: "Allarme in corso";
                            alarmType: "ALARM - 003";
                            clicked => {
                                currentPage = "AlarmDetail";
                                selectedAlarmName = self.alarmName;
                                selectedAlarmType = self.alarmType;
                            }
                        }
                    }

                    Row {
                        ActiveAlarm {
                            alarmName: "Allarme in corso";
                            alarmType: "ALARM - 007";
                        }
                    }

                    HorizontalBox {
                        height: 20px;
                    }

                    Row {

                        DisabledAlarm {
                            alarmName: "Allarme risolti";
                            alarmType: "ALARM - 001";
                        }
                    }

                    Row {
                        DisabledAlarm {
                            alarmName: "Allarme risolti";
                            alarmType: "ALARM - 002";
                        }
                    }

                    Row {
                        DisabledAlarm {
                            alarmName: "Allarme risolti";
                            alarmType: "ALARM - 002";
                        }
                    }
                }
            }
        }
    }
}
