
import { Home } from "page/home/Home.slint";
import { Lock } from "page/lock-screen/Locak.slint";
import { FontImport } from "components/home/font-import.slint";
export component index inherits Window {
    width: 800px;
    height: 480px;
    // importing font through component, 
    FontImport {
        visible: true;
    }

    in-out property <string> password: "";
    Lock {
        visible: password != "1234";
        entered_password <=> root.password;
    }

    Home {
        visible: password == "1234";
    }
}
