import { Theme } from "../../../../assets/theme/theme.slint";
import { VerticalBox, HorizontalBox, Button, GridBox } from "std-widgets.slint";
import { Header } from "../../header.slint";
import { OraTab } from "OraTab.slint";
import { DataTab } from "DataTab.slint";

component TabButton inherits VerticalBox {

    in property <length> xStyle;
    in-out property <string> activeTab;
    in property <string> tabButtonText;

    width: 370px;
    padding: 0;
    TouchArea {
        Rectangle {
            border-radius: 10px;
            background: activeTab == tabButtonText ? Theme.palette.bg.white : Theme.palette.bg.white-1;
            drop-shadow-color: #0000001A;
            drop-shadow-offset-x: 0;
            drop-shadow-offset-y: activeTab == tabButtonText ? 2px : 0;
            drop-shadow-blur: activeTab == tabButtonText ? 6px : 0;
            Text {
                text: tabButtonText;
                font-weight: 400;
                font-size: 20px;
                font-family: "Sailec-Medium";
            }
        }

        clicked => {
            activeTab = tabButtonText;
        }
    }
}

export component OraEData inherits Window {
    width: 800px;
    height: 480px;
    background: Theme.palette.gray-bg;

    in-out property <string> currentPage;
    property <string> activeTab:"Ora";

    VerticalBox {
        Header {
            currentPage <=> root.currentPage;
            previousPage: "SettingMachina";
        }

        HorizontalLayout {
            height: 68px;
            Rectangle {
                width: 100%;
                border-radius: 20px;
                border-width: 5px;
                border-color: Theme.palette.bg.white;
                HorizontalBox {
                    Rectangle {
                        background: Theme.palette.bg.white-1;
                        border-radius: 10px;
                        GridLayout {
                            padding: 5px;
                            spacing: 2px;
                            Row {
                                TabButton {
                                    activeTab <=> activeTab;
                                    tabButtonText: "Ora";
                                    col: 0;
                                }

                                TabButton {
                                    activeTab <=> activeTab;
                                    tabButtonText: "Data";
                                    col: 7;
                                }
                            }
                        }
                    }
                }
            }
        }

        if activeTab == "Ora": OraTab { }

        if activeTab == "Data": DataTab { }

        HorizontalBox {
            padding: 0;
            Rectangle {
                height: 80px;
                border-radius: 20px;
                background: Theme.palette.bg.black-1;
                HorizontalLayout {
                    padding: 10px;
                    VerticalBox {
                        padding: 10px;
                        TouchArea {
                            Image {
                                x: 240px;
                                height: 40px;
                                width: 40px;
                                source: @image-url("../../../../assets/images/file-white.svg");
                            }

                            Text {
                                text: "Salva modifiche";
                                font-weight: 400;
                                font-size: 20px;
                                vertical-alignment: center;
                                horizontal-alignment: center;
                                font-family: "Sailec-Light";
                                color: Theme.palette.text.white-1;
                            }

                            clicked => {
                                currentPage = "SettingMachina"
                            }
                        }
                    }
                }
            }
        }
    }
}
