import { Theme } from "../../../../assets/theme/theme.slint";
import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
import { Header } from "../../header.slint";

component TabButton inherits VerticalBox {

    in property <length> xStyle;
    in-out property <string> activeTab;
    in property <string> tabButtonText;

    height: 48px;
    width: 377px;
    padding: 0;
    x: xStyle;
    TouchArea {
        Rectangle {
            border-radius: 10px;
            background: activeTab == tabButtonText ? Theme.palette.bg.white : Theme.palette.gray-bg;
            Text {
                text: tabButtonText;
            }
        }

        clicked => {
            activeTab = tabButtonText;
        }
    }
}

export component OraEData inherits Window {
    width: 800px;
    height: 480px;
    background: Theme.palette.gray-bg;

    in-out property <string> currentPage;
    property <string> activeTab:"Ora";

    VerticalBox {
        Header {
            currentPage <=> root.currentPage;
            previousPage: "SettingMachina";
        }

        HorizontalLayout {
            Rectangle {
                width: 100%;
                height: 68px;
                border-radius: 20px;
                border-width: 5px;
                border-color: Theme.palette.bg.white;
                background: Theme.palette.gray-bg;
                TabButton {
                    activeTab <=> activeTab;
                    xStyle: 10px;
                    tabButtonText: "Ora";
                }

                TabButton {
                    activeTab <=> activeTab;
                    xStyle: 397px;
                    tabButtonText: "Data";
                }
            }
        }

        HorizontalLayout {
            Rectangle {
                width: 100%;
                height: 242px;
                border-radius: 20px;
                background: Theme.palette.bg.white;
                firstBox := VerticalBox {
                    padding-right: 2.5px;
                    width: 50%;
                    x: 0;
                    Rectangle {
                        border-radius: 10px;
                        background: Theme.palette.gray-bg;
                        padding: 5px;
                        HorizontalBox {
                            padding: 0;
                            height: 67px;
                            Rectangle {
                                border-radius: 10px;
                                background: Theme.palette.bg.black-1;
                            }
                        }
                    }
                }

                VerticalBox {
                    width: 50%;
                    padding-left: 2.5px;

                    x: firstBox.width;
                    Rectangle {
                        border-radius: 10px;
                        background: Theme.palette.gray-bg;
                    }
                }
            }
        }
    }
}
