import { Theme } from "../../../../assets/theme/theme.slint";
import { VerticalBox, HorizontalBox, Button } from "std-widgets.slint";
import { Header } from "../../header.slint";
export component OraEData inherits Window {
    width: 800px;
    height: 480px;
    background: Theme.palette.gray-bg;

    in-out property <string> currentPage;

    VerticalBox {
        Header {
            currentPage <=> root.currentPage;
            previousPage: "SettingMachina";
        }

        HorizontalBox {
            Rectangle {
                height: 68px;
                border-radius: 20px;
                border-width: 5px;
                border-color: Theme.palette.bg.white;
                background: Theme.palette.gray-bg;
                Button {
                    height: 48px;
                    width: 377px;
                    text: "Ora";
                }
            }
        }
    }
}
